on:
  push:
    branches:
      - master

env:
  ResourceGroup: expiration-scanner
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: build
      run: dotnet build -c Release
    - name: publish function
      run: dotnet publish -c Release --no-build ExpirationScanner/ExpirationScanner.csproj -o release/ExpirationScanner
    - uses: actions/upload-artifact@v1
      name: upload ARM artifact
      with:
        name: deploy
        path: deploy
    - uses: actions/upload-artifact@v1
      name: upload function artifact
      with:
        name: functionapp
        path: release/ExpirationScanner
    - uses: actions/upload-artifact@v1
      name: upload frontend artifact
      with:
        name: frontend
        path: wwwroot
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        name: download function artifact
        with:
          name: functionapp
          path: functionapp
      - uses: actions/download-artifact@v1
        name: download ARM artifact
        with:
          name: deploy
          path: deploy
      - uses: actions/download-artifact@v1
        name: download frontend artifact
        with:
          name: frontend
          path: frontend
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI ARM deployment
        uses: azure/CLI@v1
        with:
          inlineScript: |
            cd deploy
            chmod +x deploy.sh
            ./deploy.sh $ResourceGroup
      - uses: azure/functions-action@v1
        with:
          app-name: ${{ env.ResourceGroup }}
          package: functionapp